name: Build BOR3Y APK
on:
  push:
    branches: [ main ] # تأكد إن ده اسم البرانش عندك (main أو master)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # تحديث
      - name: set up JDK 17
        uses: actions/setup-java@v4 # تحديث
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # التحديث المهم اللي هيحل المشكلة
        with:
          name: BOR3Y-Final-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
